# Site settings
title: Isaque Dias - Empreendedor e Desenvolvedor Web
email: isaquediasm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog de um desenvolvedor Front End e entusiasta de novas tecnologias.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://isaquedias.com.br" # the base hostname & protocol for your site
twitter_username: isaquediasm
github_username:  isaquediasm

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Séries
    url: /series
  - title: Tags
    url: /tags
  - title: Sobre mim
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
